package synthesizer

import (
	"fmt"
	"math/rand"
	"regexp"
	"strings"

	"github.com/garypwhite/flowerytalk/internal/g2p"
)

var p = g2p.NewPhonemizer()

// Returns a list of files, making a sentence to be generated by the "engine"
// Will attempt the word files first, then call for phonemes to be resolved.
// Phoneme handler function can also put sounds together for unknown words.
func (s Synthesizer) ResolveSentenceFiles(sentence string) ([]string, error) {
	fullSentenceFiles := []string{}
	re := regexp.MustCompile(`[^A-Za-z\s!?.,']`)
	punct := regexp.MustCompile("([!?.,])")
	sentence = re.ReplaceAllString(sentence, "")        // remove unneeded punct
	sentence = punct.ReplaceAllString(sentence, " $1 ") // add padding to parse punct
	for _, word := range strings.Split(sentence, " ") {
		if len(word) == 0 { // double spaces, etc. do not add anything
			continue
		}
		if punct.Match([]byte(word)) { // add punctuation by itself
			fullSentenceFiles = append(fullSentenceFiles, word)
			continue
		}
		// check if word file exists.
		wordFile, ok := s.resolveWordFile(word)
		if ok {
			fullSentenceFiles = append(fullSentenceFiles, wordFile)
			continue
		}
		phonemeList := p.ParseWord(word)
		phonemeList, err := s.resolvePhonemeFiles(phonemeList)
		if err != nil {
			return nil, err
		}
		fullSentenceFiles = append(fullSentenceFiles, phonemeList...)

	}
	return fullSentenceFiles, nil
}

// Attempt to use full words as provided. This will frequently not exist,
// so we return the "ok" second argument.
func (s Synthesizer) resolveWordFile(word string) (string, bool) {
	wordsList, ok := s.words[strings.ToLower(word)]
	if !ok {
		return "", ok
	}
	idx := rand.Intn(len(wordsList))
	return wordsList[idx], true
}

// Returns a list of files (embedded) for a given list of phonemes.
// These phoneme files can be given to LoadAudioClips to get sound file contents.
// Gives an error when no phoneme can be found, even in fallbacks.
// When a phoneme is not found, a list of fallbacks will be given. Fallback list is
// about 3x larger, and is sorted by the provided manifest.json (best-match-first)
func (s Synthesizer) resolvePhonemeFiles(phonemes []string) ([]string, error) {
	allFiles := make([]string, len(phonemes))
	punct := regexp.MustCompile(punct_regexp) // detect punctuation to add silence/pauses
	for i, p := range phonemes {
		if punct.Match([]byte(p)) {
			allFiles[i] = p
			continue
		}

		files, ok := s.clips[p]
		if ok {
			idx := rand.Intn(len(files))
			allFiles[i] = files[idx]
			continue
		}
		// could not find any clips for phoneme, try fallbacks
		fbFiles := []string{}
		fallbacks, ok := s.fallbacks[p]
		for _, fb := range fallbacks {
			files, ok := s.clips[fb]
			if ok { // TODO: could add some randomness here, shuffle fallbacks before `range`ing it
				fbFiles = append(fbFiles, files...)
				break // let's use the first found suggestion...
			}
		}
		if !ok || len(fbFiles) == 0 { // check both failure conditions, no fallback and/or no fallback files
			return allFiles, fmt.Errorf("Could not produce phoneme for <%s>, no phoneme or fallback found.", p)
		}
		idx := rand.Intn(len(fbFiles))
		allFiles[i] = fbFiles[idx]
	}
	return allFiles, nil
}
